# Generated by Django 4.2.20 on 2025-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_event_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_pacbi",
            field=models.BooleanField(default=False, verbose_name="🇵🇸 PACBI"),
        ),
    ]
